spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.20.88.141:9092
          auto-add-partitions: true
          producer-properties:
            key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bindings:
        # 消息生产者
        actuatorStatusReport-out-0:
          destination: actuator_status_report
          content-type: application/json
          binder: kafka
        confirmDataCenterCallBack-out-0:
          destination: confirm_data_center_call_back
          content-type: application/json
          binder: kafka
        # 消息消费者
        confirmDataCenter-in-0:
          destination: confirm_data_center
          content-type: application/json
          group: ${data.center.id}
          binder: kafka
      function:
        definition: confirmDataCenter