spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.20.81.156:9092
      bindings:
        # 测试
        testProducer-out-0:
          destination: test-group-topic
          content-type: application/json
          binder: kafka
        testConfirmDataCenter-out-0:
          destination: confirm_data_center
          content-type: application/json
          binder: kafka
        # 消息生产者
        actuatorStatusReport-out-0:
          destination: actuator_status_report
          content-type: application/json
          binder: kafka
        confirmDataCenterCallBack-out-0:
          destination: confirm_data_center_call_back
          content-type: application/json
          binder: kafka
        generateKeyCallBack-out-0:
          destination: generate_key_call_back
          content-type: application/json
          binder: kafka
        # 消息消费者
        confirmDataCenter-in-0:
          destination: confirm_data_center
          content-type: application/json
          group: ${data.center.id}
          binder: kafka
        generateKey-in-0:
          destination: generate_key
          content-type: application/json
          group: ${data.center.id}
          binder: kafka
      function:
        definition: confirmDataCenter;generateKey