server:
  port: 8022
  servlet:
    context-path: /csp/actuator
spring:
  application:
    name: csp-actuator-server
  profiles:
    active: kafka

logging:
  config: classpath:logback-config.xml
  level:
    org.apache.kafka: warn

log:
  path: /opt/csp-actuator
  # 日志输出格式
  pattern: "%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{36}) %yellow(-[%file:%line]-) %msg%n"
  # 日志输出级别
  root:
    level: info
  # 日志最大历史天数
  max-history: 60
  # 日志总文件大小
  total-size-cap: 10GB

# kms地址
kms:
  address: default
  secret: 0D9Qe30GIMm6oYTcDTuRQgRy7G7R6AMm

# 数据中心地址以及kafka地址
data:
  kafka:
    address: 172.20.88.141:9092
  center:
    id: default
    name: default

# 定时上报为启动之后的5min为第一次，后续每5min上报一次
node:
  report:
    initialDelay: 5
    fixedDelay: 5

# Topic消息数据时效性: 10min
msg:
  effective:
    time: 10