server:
  port: 8022
  servlet:
    context-path: /csp/actuator
spring:
  application:
    name: csp-actuator-server
  profiles:
    active: kafka

logging:
  level:
    org.apache.kafka: warn

# kms地址
kms:
  address: default
  secret: 0D9Qe30GIMm6oYTcDTuRQgRy7G7R6AMm

# 数据中心地址
data:
  center:
    id: default
    name: default

# 定时上报为启动之后的5min为第一次，后续每5min上报一次
node:
  report:
    initialDelay: 5
    fixedDelay: 5

# Topic消息数据时效性: 10min
msg:
  effective:
    time: 10